### ISSUE TITLE
Design doc review #2 - Sample State

### ISSUE THREAD

**Issue by aracpyon** [iamdanahn/RunWithMe#2]
**Sample State**
- [x] Remove routes and friends
- [x] create `workouts` slice of state
- [x] `friending` is a joins table to show how many friends you have. Instead of saving, multiple friends at once, `friendId` will contain one friend at a time. So if the `currentUserId` is 1, friending should show all the data of which userId is 1. Like Pokemon Items on Pokedex project.

**Comment by aracpyon** [comment]
- [x] Remove `allRoutes` from the `routes`
- [x] Remove `allUsers` from the `users`
- [x] Remove `allComments` from the `comments`
- [x] Your currentUserId is `90`. Then your workout's user_id should be 90 because workouts that belongs to the currentUser will be shown. 
- [x] friending only shows the currentUser's friends. Either do this or add `freindsId` slice to `Users` such as:
```js
{
  entities: {
    users: {
      5: {
        id: 5,
        username: 'Eric O.',
        friendsId: [1, 3, 4] //=> this is coming from friendings table through `user.friends_id` method.
      },
      6: {
        id: 6,
        username: 'Felicia C.',
        friendsId: [5, 3]
      },
      7: {
        id: 7,
        username: 'Gary P.',
        friendsId: [8, 9]
      }
    },
``` 
But if you do this, you should remove `friending` slice from your entities to keep the one source of truth rule. 
- [x] Add `start_pos_lat`, `start_pos_lng`, `end_pos_lat`, `end_pos_lng` to `routes`

**Comment by iamdanahn** [comment]
- Changed friends slice to hold only current user's friends
- Added `email`, `birthday`, and `gender` to all users

**Comment by aracpyon** [comment]
Great! Your sample state looks good to go.
