### ISSUE TITLE
Design doc review #3 - backend and frontend routes

### ISSUE THREAD

**Issue by aracpyon** [iamdanahn/RunWithMe#3]
**Backend routes**
- [x] `GET /api/routes` - `route's home page` => To get all the routes that only belongs to the currentUser / `search bar for routes` => To get the list of routes that matches with the keyword given by the user. 
- [x] `GET /api/friends` - return all friends => all the friends that currentUser has. 

**Frontend routes**
- [x] `/users` Is this for friends' search? Then let's change it to `/friends` This route will show the list of friends the currentUser has. 
- [x] `/friends/find` a route for searching friends. It will give us a search bar and show the result. 
- [x] `/dashboard/routes` => Let's change this to `/routes/search` for search because on MapMYRun, `dashboard` and `routes` are separate tabs. (`dashboard` is under `workouts` and `find routes` is under `Routes` tab. `/routes/search` will be for `find routes`
- [x] add `/routes/create` route. This page will render a google map so user can draw a route. After you are done with the User auth MVP, this is going to be your first page you will need to build as for 3rd MVP. Think about what components you will need for this route and update it. 
- [x] add `/routes` for `my routes` under the `Routes` tab. This will show all the routes the currentUser has. (Basically `RouteIndex component` that's rendering `RouteIndexItem child component`). On each `routeIndexItem`, it will have buttons for `edit`, `delete`. 
- [x] `/dashboard/routes/:id` => change it to `/routes/:id`. But you don't need this route because MapMyRun doesn't have route's show page. Instead it has `edit` page. 
- [x] That being said, let's add a route `/routes/:id/edit` for the route edit page. This will render google map again so the user can redraw the route.

**Comment by iamdanahn** [comment]
All points fixed!

**Comment by aracpyon** [comment]
- [x] I don't see `/routes/create`!

**Comment by iamdanahn** [comment]
Omg lol added it now

**Comment by aracpyon** [comment]
Awesome! :)
